

POST https://localhost:7213/api/auth/register
Content-Type: application/json

{
    "FirstName": "Masum",
    "LastName": "Billah",
    "Email": "masumcsepust@gmail.com",
    "Password": "mdkms12345"
}